version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: 'bundler'
  directory: '/'
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: "devcontainers"
  directory: "/"
  schedule:
    interval: weekly
