name: deb
on:
  workflow_call:
  push:
    branches: [ planted ]
  pull_request:
    branches: [ planted ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86, pi, pi-zero]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - uses: actions/setup-node@v4
        with:
          node-version: 18.13.0
      - uses: actions/cache@v4.2.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: yarn
      - name: build
        run: make ${{ matrix.target }}
      - name: bundler
        run: gem install bundler -v 2.4 --no-document
      - name: fpm
        run: bundle install
      - name: deb
        run: make ${{ matrix.target }}_deb
      - name: "Upload deb package"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-deb
          path: 'reef-pi-*.deb'
          if-no-files-found: error
          retention-days: 30
