name: go
on:
  workflow_call:
  push:
  pull_request:
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - uses: codecov/codecov-action@v4.5.0
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: make lint
      - run: make race
