name: go
on: [push, pull_request]
jobs:
  builds:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      #- uses: codecov/codecov-action@v3.1.4
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: make lint
      - run: make race
