name: Release
on:
  release:
    types:
      - created
  pull_request:
    branches:
      - planted
jobs:
  build:
    uses: ./.github/workflows/deb.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: x86-debian-package
      - uses: actions/download-artifact@v4
        with:
          name: pi0-debian-package
      - uses: actions/download-artifact@v4
        with:
          name: pi3-debian-package
      - run: ls
#      - name: Upload deb package
#        uses: AButler/upload-release-assets@v3.0
#        with:
#          files: "*.deb"
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
