name: Release
on:
  release:
    types:
      - created
jobs:
  build:
    uses: ./.github/workflows/deb.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: x86-debian-package
      - uses: actions/download-artifact@v4
        with:
          name: pi0-debian-package
      - uses: actions/download-artifact@v4
        with:
          name: pi3-debian-package
      - name: Upload deb package
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "reef-pi-*.deb"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
