name: Release
on:
  push:
    branches:
      - planted
jobs:
  go:
    uses: ./.github/workflows/go.yml
  jest:
    uses: ./.github/workflows/jest.yml
  translations:
    uses: ./.github/workflows/translations.yml
  smoke:
    uses: ./.github/workflows/smoke_.yml
  deb:
    uses: ./.github/workflows/deb.yml
  release:
    needs:
      - jest
      - deb
      - go
      - translations
      - smoke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - uses: actions/setup-node@v4
        with:
          node-version: 18.13.0
      - uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: yarn
      - name: pi-zero
        run: make pi-zero
      - name: bundler
        run: gem install bundler -v 2.4 --no-document
      - name: fpm
        run: bundle install
      - name: deb
        run: make pi_deb

      - run: ls *.deb
