name: smoke
on:
  workflow_call:
  push:
    branches: [ planted ]
  pull_request:
    branches: [ planted ]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4.2.3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - run: make install
      - run: make go
      - run: make ui
      - run: |
          make start-dev &
          make smoke
