name: translation
on:
  workflow_call:
  push:
    branches: [ planted ]
  pull_request:
    branches: [ planted ]
jobs:
  Translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4.2.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: yarn
      - name: Check Translations
        run: yarn run translations:chk
